"""fresh start

Revision ID: 6c9da3d2e276
Revises: 9d6b66f692c4
Create Date: 2026-04-01 22:21:04.267930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9da3d2e276'
down_revision: Union[str, Sequence[str], None] = '9d6b66f692c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_asset_project_id_fkey', 'assets', type_='foreignkey')
    op.drop_constraint('chunks_chunk_project_id_fkey', 'chunks', type_='foreignkey')
    op.drop_constraint('projects_Project_uuid_key', 'projects', type_='unique')
    op.drop_column('projects', 'Project_uuid')
    op.drop_column('projects', 'Project_id')
    op.add_column('projects', sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_primary_key('projects_pkey', 'projects', ['project_id'])
    op.add_column('projects', sa.Column('project_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'projects', ['project_uuid'])
    op.create_foreign_key(None, 'assets', 'projects', ['asset_project_id'], ['project_id'])
    op.create_foreign_key(None, 'chunks', 'projects', ['chunk_project_id'], ['project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('Project_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('Project_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_unique_constraint(op.f('projects_Project_uuid_key'), 'projects', ['Project_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'project_uuid')
    op.drop_column('projects', 'project_id')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_chunk_project_id_fkey'), 'chunks', 'projects', ['chunk_project_id'], ['Project_id'])
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_asset_project_id_fkey'), 'assets', 'projects', ['asset_project_id'], ['Project_id'])
    # ### end Alembic commands ###
